import type { Metadata } from "next";
import "./globals.css";
import { Registry } from "./registry";

import { Roboto } from "next/font/google";
import { NavBar } from "@/components/header";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable} suppressHydrationWarning>
      <head>
        <meta httpEquiv="Access-Control-Allow-Origin" content="*" />
      </head>
      <Registry>
        <NavBar />
        {children}
      </Registry>
    </html>
  );
}
