import type { Metadata } from "next";
import "./globals.css";
import { Registry } from "./registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta httpEquiv="Access-Control-Allow-Origin" content="*" />
      </head>
      <Registry>{children}</Registry>
    </html>
  );
}
