import type { Metadata } from "next";
import "./globals.css";
import { Registry } from "./registry";
import { ThemeProvider } from "@/components/theme";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta httpEquiv="Access-Control-Allow-Origin" content="*" />
      </head>
      <Registry>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextTopLoader color="#fff" showSpinner={false} />
            {children}
          </ThemeProvider>
        </body>
      </Registry>
    </html>
  );
}
